### ISSUE TITLE
[Feature] HomeView

### ISSUE THREAD

**Issue by 22Seongsoo** [DeveloperAcademy-POSTECH/MC2-Team14-OXY#15]
## Description
HomeView UI 구현, 방만들기와 입장하기 버튼
## Etc
1. 커스텀 폰트는 각자 임포트 해야하는 건가요?
2. 네비게이션 경로로 지정할 뷰 이름

**Comment by imparang** [comment]
제가 커스텀 폰트 임포트했어요.

```
Text("~~~") 
    .font(.custom("Pretendard-{font-weight}", size: {size})
```
위처럼 사용하시면 됩니당

**Comment by imparang** [comment]
네비게이션 경로로 사용할 뷰 이름은
CreateMeetingRoomView  -> 방만들기누르면 나오는 뷰

방만들기만 네비게이션으로 사용하시고 입장하기는 카메라를 띄워야 해서 버튼만 들어주세요.
